/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "uart.h"
#include "flash.h"
#include "global.h"
#include "config.h"
#include "define.h"
#include "xprintf.h"

#include "system_g031.h"
#include "stm32g031xx.h"
#include <string.h>
#include <stdlib.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define ENABLLE_BOOTLOADER		1
#define BOOT_PRIMARY_ADDRESS    0x8002800
t_APP_CONFIG g_config;

uint32_t ulMiliCount = 0;
uint32_t ulSecCount = 0;
uint32_t ulTickCount = 0;

uint32_t static lastPrintTest = 0;

static int setup(void);
static void printTest(void);

int main(void) {
#if ENABLLE_BOOTLOADER
	SCB->VTOR = (uint32_t) BOOT_PRIMARY_ADDRESS;
	__DSB();
	__enable_irq();
#endif
	setup();
	while (1){
		printTest();
	}

}

static int setup(void) {
	systemInit();
	usart_x0_init(115200);
	xdev_out(usart_x0_sendChar);
	return 0;

}

void SysTick_Handler(void) {
	ulMiliCount++;
	ulTickCount++;
	if (ulTickCount >= 1000) {
		ulSecCount++;
	}
}
static void printTest(void) {
	if ((uint32_t) (ulMiliCount - lastPrintTest) >= 1000) {
		lastPrintTest = ulMiliCount;
		xprintf("hello, it test print, Thank!!!\r\n");

	}
}
