/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
volatile uint32_t ulMiliCount = 0;
volatile uint32_t ulSecCount = 0;
static uint32_t ulTickCount = 0;

#define COM_X0_RX_SIZE			20
uint8_t com_x0_rx_buf[COM_X0_RX_SIZE];

uint32_t lastPushData = 0;
static void setup(void);

int main(void) {
	setup();
	while (1) {
		/*if ((uint32_t) (ulMiliCount - lastPushData) > 5000) {
			lastPushData = ulMiliCount;
			xprintf("hello it'test uart\r\n");
		}*/
	}
	return 0;
}

static void setup(void) {
	usart_x0_init(115200);
	xdev_out(usart_x0_send);
	dma_init(DMA1_Channel1);
	dma_config(DMA1_Channel1,(uint32_t) &USART1->RDR, (uint32_t)com_x0_rx_buf, COM_X0_RX_SIZE);
	NVIC_SetPriority (DMA1_Channel1_IRQn, 0);
	NVIC_EnableIRQ (DMA1_Channel1_IRQn);
}

void SysTick_Handler(void) {
	ulMiliCount++;
	ulTickCount++;
	if (ulTickCount > 1000) {
		ulTickCount = 0;
		ulSecCount++;
	}
}
