/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "main.h"
#include "system_g031.h"


volatile uint32_t ulMiliCount = 0;
volatile uint32_t ulSecCount = 0;

static uint32_t ulTickCount = 0;
static uint32_t lastSendData = 0;

static int setup(void);
extern void mainboot(void);
int main(void) {
	setup();
	mainboot();
	return 0;
}

static int setup(void) {
	int ret = 0;
	systemInit();
	usart_x0_init(19200);
	CRC_ClockInit();
	xdev_out(SerialPutChar);
	return ret;
}

void SysTick_Handler(void) {
	ulMiliCount++;
	ulTickCount++;
	if (ulTickCount > 1000) {
		ulTickCount = 0;
		ulSecCount++;
	}
}
